### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Mykolb**

### CODE REVIEW

**Review by secantsquared — COMMENTED** [review]
@Mykolb 
Git work flow set up correctly
Thank you

**Review by secantsquared — APPROVED** [review]
@Mykolb 
This is looking pretty darn good! WOW! 
Excellent use of flex in achieving the 2X3 structure - love that
Way to use those responsive units too its very smooth as it moves across viewports

🔥🔥🔥🔥

**Review by secantsquared — CHANGES_REQUESTED** [review]
I love the layout and what you did since last time.
Text at that lower breakpoint is hard to deal with, and I run into the same issues, try to decrease the REM a little bit and its okay if you want to either stack them all on top of each other so you have one column at your mobile viewports or if you want to maybe consider collapsing them into tabs, but if you set up a media query and get those to flex to a single column it would help with the text issue since you would have one box in the viewport instead of two ... just like the great idea page where it all goes into one big column... that could help those issues, other wise keep going - love it and I really like that color at the lower breakpoints... one of my favs

**Comment by Mykolb** [comment]
Thanks for the help!

**Review by secantsquared — APPROVED** [review]

**Review by secantsquared — APPROVED** [review]
The box shadows on the boxes and the 2 x 2 layout looks so professional and clean.  I love it.  Incredible I love watching it evolve over time.  This is a very nice layout.

**Pull request merged**
